sudo: required
dist: precise

os:
    - linux
    - osx

language: go
go:
- tip # The latest version of Go.

install:
 - go get -d -t -v ./...
 - go test -v ./...
 - go build -v ./...

script:
 - sh ./testing/run_travis_tests.sh
